# Generated by Django 5.0.6 on 2024-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('shopper', 'Shopper'), ('retailer', 'Retailer')], default='shopper', max_length=10),
        ),
    ]
