# Generated by Django 5.0.6 on 2024-08-01 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_cart_user_alter_cartitem_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='InventoryCartItem',
        ),
        migrations.CreateModel(
            name='InventoryCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(through='inventory.InventoryCartItem', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='inventorycartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_cart_items', to='inventory.inventorycart'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
