# Generated by Django 5.0.6 on 2024-08-21 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_cartitem_inventorycartitem_inventorycart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorycartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_cart_items_set', to='inventory.inventorycart'),
        ),
        migrations.AlterField(
            model_name='inventorycartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_cart_items_inventory', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_order_items_inventory', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_order_items_set', to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShopperCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopper_inventory_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopperCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopper_inventory_cart_items_set', to='inventory.shoppercart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopper_inventory_cart_items_inventory', to='inventory.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='shoppercart',
            name='items',
            field=models.ManyToManyField(related_name='shopper_inventory_cart_items', through='inventory.ShopperCartItem', to='inventory.inventoryitem'),
        ),
    ]
